language: php

sudo: false

# Move from what was the default LTS distro, trusty, to the next supported one, xenial.
dist: xenial
# Services are now disabled by default.
# Ref: https://docs.travis-ci.com/user/reference/xenial/#differences-from-the-trusty-images .
services:
  - mysql
  - postgresql

addons:
  firefox: "47.0.1"
  apt:
    packages:
      - openjdk-8-jre-headless
      - postgresql-9.3

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.0
  - 7.1
  - 7.2

env:
  - DB=pgsql  MOODLE_BRANCH=MOODLE_33_STABLE NODE_VERSION=8.9
  - DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE NODE_VERSION=8.9
  - DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE NODE_VERSION=8.9
  - DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE NODE_VERSION=14.4
  - DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE NODE_VERSION=8.9
  - DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE NODE_VERSION=14.4
  - DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE NODE_VERSION=14.4
  - DB=pgsql  MOODLE_BRANCH=master           NODE_VERSION=14.4

matrix:
  include:
    - php: 5.6
      env: DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE NODE_VERSION=8.9  # Moodle 3.4+ requires PHP 7.0+.
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE NODE_VERSION=14.4 # Moodle 3.7+ runs on PHP 7.3.
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE NODE_VERSION=14.4
    - php: 7.3
      env: DB=pgsql  MOODLE_BRANCH=master           NODE_VERSION=14.4
    - php: 7.4
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE NODE_VERSION=14.4 # Moodle 3.8.3+ runs on PHP 7.4.
    - php: 7.4
      env: DB=pgsql  MOODLE_BRANCH=master           NODE_VERSION=14.4
  exclude:
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE NODE_VERSION=14.4 # Moodle 3.7+ requires PHP 7.1+.
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE NODE_VERSION=14.4
    - php: 7.0
      env: DB=pgsql  MOODLE_BRANCH=master           NODE_VERSION=14.4
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=master           NODE_VERSION=14.4 # Moodle 3.9+ requires PHP 7.2+.
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE NODE_VERSION=8.9
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_33_STABLE NODE_VERSION=8.9

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
